# Generated by Django 5.2.1 on 2025-05-21 18:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
