# Generated by Django 5.2.1 on 2025-05-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(),
        ),
    ]
